### ISSUE TITLE
Remove protectedTokens

### ISSUE THREAD

**Issue by Grandthrax** [yearn/yearn-vaults#241]
protectedTokens serves no purpose and is in fact dangerous. It is there to stop governance from 'sweeping' out want and other protected tokens. But why do we want this? It adds no extra safety as governance has that ability with migrateStrategy. But if migrateStrategy is broken then we could end up with tokens locked forever.

**Comment by dougstorm** [comment]
I get the point of having a way to save the tokens from a broken strategy but i think we can mitigate that with the review and testing process we have, as we enforced tests for migration are passing before live testing. Also we can limit new strategy debtRatio until we can test a migration in ganache fork.

I am presenting the options since im of the opinion that it's a security feature that governance cannot access the `want` tokens of a vault for the users and is presented as such in other mediums:
https://rekt.news/meerkat-finance-bsc-rekt/

In the future if governance is switched to a timelocked contract and new strategies can be signaled, but if we remove protected tokens, a hijacked vault by a malicious governance won't give time for the users to react with the `sweep` function.

So yeah it's a trade off for sure but i think like the non upgradable contracts is something that gives users trust in the code, it just becomes an operational issue when deploying new strategies as mentioned above.

**Comment by dougstorm** [comment]
Also referencing this PR #243, i think is just the same for strategist to leave protectedTokens as an empty list and choose to leave sweep available. Even with these changes we can still potentially have `want` tokens locked. 

So not sure there is much value in removing them if we are not removing the `want` check in any case, since protectedTokens was always up to the strategist to implement
