### ISSUE TITLE
Performance fees can total more than 100%

### ISSUE THREAD

**Issue by steffenix** [yearn/yearn-vaults#321]
Change the maximum set point for both to be 50% (which ensures they are never more than 100%)

**Comment by steffenix** [comment]
I have looked again at the issue and I think we were not looking at the right part of the code yesterday.

The issue is on setting the vault performanceFee once a strategy has been added.
```
@external
def setPerformanceFee(fee: uint256):
    """
    @notice
        Used to change the value of `performanceFee`.

        Should set this value below the maximum strategist performance fee.

        This may only be called by governance.
    @param fee The new performance fee to use.
    """
    assert msg.sender == self.governance
    assert fee <= MAX_BPS
    self.performanceFee = fee
    log UpdatePerformanceFee(fee)

```

**Comment by steffenix** [comment]
@fubuloubu 
you have suggested to update

```
    assert performanceFee <= MAX_BPS - self.performanceFee
```

And make sure the perfomanceFee isn't more than

**Comment by fubuloubu** [comment]
> The issue is on setting the vault performanceFee once a strategy has been added.

Correct. As there is no way to get `max(performanceFee for performanceFee in self.strategies)`, there is no way to limit that setting to ensure the 100% invariant is maintained.

Making the maximum 50% is a shortcut around it. Since the governance fee can't be set to >50%, and each strategy can't be set to >50%, the total can therefore never be >100%.
