### ISSUE TITLE
Clarification regarding `estimatedTotalAssets`

### ISSUE THREAD

**Issue by Pet3ris** [yearn/yearn-vaults#456]
In https://github.com/yearn/yearn-vaults/blob/main/contracts/BaseStrategy.sol#L517, this line says:

> This value should be higher than the total debt of the Strategy and higher than its expected value to be "safe"

Should the second "higher" be replaced with "lower" instead? Like so.

> This value should be higher than the total debt of the Strategy and **lower** than its expected value to be "safe"

**Comment by fubuloubu** [comment]
The sentence is a little nonsensical if you ask me. The first part is fine, "This value should be higher than the total debt of the Strategy **during normal operation**" but the second part I am not sure what the intent is.

`estimatedTotalAssets` is an "expected value" so I am not sure it can be higher than itself. I'm not sure what the safety property mentioned is relying on, overall the safety property is not to rely on this value for determining actual value because the property could be manipulated by external sources quite easily.
