### ISSUE TITLE
Potential Harvest Sandwich Attack

### ISSUE THREAD

**Issue by 0x0scion** [yearn/yearn-vaults#519]
(Issue edited by yearn team)

**Comment by storming0x** [comment]
Hey @0x0scion since this issue is related to security please follow the guide here to report the issue.

https://github.com/yearn/yearn-security/blob/master/SECURITY.md

Currently we are looking at the issue and agree that this is highly unlikely to be pulled off in production given our current mitigations for similar attacks, (healthchecks that avoid reporting a loss unchecked), flashbot managed harvests, etc.

With that said we always look into the issues and if this is a viable one the best way to report it is the guide above to get included as bounty, we also have immunefi support if you want to go over them to report it too.

Thanks.
